name: Build

on:
  - push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install SQLite3
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y sqlite3

      - uses: actions/checkout@v4

      - uses: mlugg/setup-zig@v1
        with:
          version: master

      - run: zig build test --summary all
